---
title: "Tugas Akhir TPM"
author: "Angga Fathan Rofiqy"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: true
    highlight: tango
    code_folding: hide
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    fig_caption: true
pkgdown:
  as_is: true
---

```{r setup, include=FALSE, echo=FALSE, warning=FALSE, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
#                      -=( Install & Load Package Function )=-
install_load <- function (package1, ...)  {   

   # convert arguments to vector
   packages <- c(package1, ...)

   # start loop to determine if each package is installed
   for(package in packages){

       # if package is installed locally, load
       if(package %in% rownames(installed.packages()))
          do.call('library', list(package))

       # if package is not installed locally, download, then load
       else {
          install.packages(package)
          do.call("library", list(package))
       }
   } 
}

path <- function() gsub  ( "\\\\",  "/",  readClipboard ()  )

install_load("readxl","ggplot2","dplyr","DT","cowplot")

export.chart <- "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 6/2. Teknik Pembelajaran Mesin/Project/Chart"
```

```{r , include=FALSE, echo=FALSE, warning=FALSE, message = FALSE}
#Set Working Directory
require("knitr")
opts_knit$set(root.dir = "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 6/2. Teknik Pembelajaran Mesin/Project/Tugas Kelompok")
```

# Data

## Input Data

```{r}
raw.data <- read.csv("Data.csv"); data <- raw.data
colnames(data) <- c("Prov","X1","X2",'X3','X4','X5','X6','X7')
datatable(raw.data,  options = list(pageLength = 5))
```

## Check Data

> **Cek tipe data**

```{r}
str(raw.data)
```

```{r}
data <- data %>%
  mutate(across(-1, as.numeric))
str(data)
```

> **Cek data hilang**

```{r}
colSums(is.na(raw.data))
```

Tidak ada data hilang pada setiap kolom.

## Eksplorasi data {.tabset}

> **Sebaran data**

```{r fig.height=15, fig.width=35, dpi=300}
par(mfrow = c(3,3))
hist(data[,2], main="X1 - UHH", cex.main=4)
hist(data[,3], main="X2 - Puskesmas", cex.main=4)
hist(data[,4], main="X3 - Imun", cex.main=4)
hist(data[,5], main="X4 - Tenaga Medis", cex.main=4)
hist(data[,6], main="X5 - BPJS", cex.main=4)
hist(data[,7], main="X6 - Sanitasi", cex.main=4)
hist(data[,8], main="X7 - Sumber Air", cex.main=4)
```

```{r}
i=2
  p1 <- ggplot(data, aes(x = data[,1+i] )) +
    geom_density(color = colors[2,i], fill="blue", lwd=4) +
    ylab("Density") + theme_void()
p1
p2
plots
plot_grid(plotlist = all_plots, ncol=2)
```

```{r fig.height=18, fig.width=30, dpi=300}
colors <- data.frame(c("#d83a00", "#ff5d2d", "#feb9a5"),
                     c("#a86403", "#ca8501", "#f9e3b6"),
                     c("#0b827c", "#06a59a", "#acf3e4"),
                     c("#3a49da", "#5867e8", "#bec7f6"),
                     c("#7526e3", "#9050e9", "#d7bff2"),
                     c("#9602c7", "#cb65ff", "#e5b9fe"),
                     c("#b60554", "#ff538a", "#fdb6c5"))
titles <- c("\nX1 - UHH","\nX2 - Puskesmas","\nX3 - Imun","\nX4 - Tenaga Medis",
            "\nX5 - BPJS", "\nX6 - Sanitasi","\nX7 - Sumber Air")
bin <- c(.8, 85, 10, 700, 7, 5, 6)
all_plots <- list()

for (i in 1:(ncol(data)-1) ) {
  plots <- list()
  
  # Histogram with density plot
  p1 <- ggplot(data, aes(x = data[,1+i] )) +
    geom_histogram(aes(y = ..density.., weight=data[,1+i] ), 
                   binwidth = bin[i], 
                   fill = colors[2,i], color = "black", alpha = 0.75, lwd=1) +
    geom_density(color = colors[1,i], lwd=4) +
    ylab("Density") + theme_void()
  
  # Boxplot
  p2 <- ggplot(data, aes(y = data[,1+i] )) +
    geom_boxplot(fill = colors[3,i], color = "black", 
                 outlier.size = 3, lwd=1) +
    xlab("Nilai") + theme_void() + coord_flip()
  
  # Gabung plot
  combined_plot <- plot_grid(p1, p2, ncol = 1, align = 'v', 
                             rel_heights = c(1, 0.15))
  
  # Menambahkan judul utama
  title <- ggdraw() + 
    draw_label(titles[i], fontface = 'bold', x = 0.5, 
               hjust = 0.5, size = 20)
  
  # Menampilkan plot dengan judul utama
  plots <- 
  plot_grid(title, combined_plot, ncol = 1, rel_heights = c(0.1, 1))
  
  all_plots[[i]] <- plots
}
plot_grid(plotlist = all_plots, ncol=3)
```

```{r}
d <- density(data$X1)
plot(d, main="Kernel Density of Miles Per Gallon")
polygon(d, col="red", border="blue")
```
